{{- define "certificate-lib.certificate" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: {{ .name }}-certificate
    labels:
        app.kubernetes.io/managed-by: Helm
spec:
    secretName: {{ .name }}-certificate
    issuerRef:
        name: {{ .name }}-issuer
    dnsNames: 
        {{- range .hosts }}
        - {{ . }}
        {{- end  }}
{{- end }}