{{- define "certificate-lib.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  secret-access-key: {{ .secretAccessKey | b64enc | quote }}
{{- end -}}
