image: registry.gitlab.com/solveq/mykross/backend/docker-kubectl-helm-aws-doppler
services:
    - docker:dind

workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
          when: never
        - if: '$CI_COMMIT_BRANCH'
        - if: '$CI_COMMIT_TAG'

.envsubst-env: &envsubst-env
    - cd _helm/dashboard
    - cat values.yaml | envsubst | sponge values.yaml
    - cd values
    - doppler run -t $DOPPLER_TOKEN_ROUTE53 -- sh -c "cat route53.yml | envsubst | sponge route53.yml"
    - doppler run -t $DOPPLER_TOKEN_MAIN -- sh -c "cat $ENV.yml | envsubst | sponge $ENV.yml"
    - cd ../../..

.configure-aws: &configure-aws
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - $(aws ecr get-login --no-include-email)

.setup-aws-kubernetes: &setup-aws-kubernetes
    - aws eks --region eu-west-1 update-kubeconfig --name kross-test
    - kubectl get svc

.dry-run: &dry-run
    - cd _helm/dashboard
    - 'helm upgrade --dry-run --install --create-namespace --namespace dashboard-$ENV -f values.yaml -f values/$ENV.yml -f values/route53.yml dashboard .'
    - cd ../..

.deploy-script: &deploy-script
    - cd _helm/dashboard
    - 'helm upgrade --atomic --install --create-namespace --timeout 3m0s --wait --cleanup-on-fail --namespace dashboard-$ENV -f values.yaml -f values/$ENV.yml -f values/route53.yml dashboard .'
    - cd ../..

stages:
    - build
    - deploy

build:
    stage: build
    rules:
        - if: '$CI_COMMIT_REF_NAME == "master"'
          when: always
        - if: '$CI_COMMIT_REF_NAME != "master"'
          when: manual
    before_script:
        - *configure-aws
    script:
        - TAG="$CI_COMMIT_SHORT_SHA" docker compose -f docker-compose.yml -f docker-compose.prod.yml build dashboard
        - TAG="$CI_COMMIT_SHORT_SHA" docker compose -f docker-compose.yml -f docker-compose.prod.yml push dashboard

.deploy:
    stage: deploy
    dependencies:
        - build
    before_script:
        - *configure-aws
        - *setup-aws-kubernetes
        - TAG="$CI_COMMIT_SHORT_SHA" docker compose -f docker-compose.yml -f docker-compose.prod.yml pull dashboard
    script:
        - *envsubst-env
        - *dry-run
        - *deploy-script

deploy-test:
    extends:
        - .deploy
    rules:
        - if: '$CI_COMMIT_REF_NAME != "master"'
          when: manual
    variables:
        DOPPLER_TOKEN_MAIN: $DOPPLER_TOKEN_MAIN_PRE
        DOPPLER_TOKEN_ROUTE53: $DOPPLER_TOKEN_ROUTE53_PRE
        ENV: pre

deploy-pre:
    extends:
        - .deploy
    rules:
        - if: '$CI_COMMIT_REF_NAME != "master"'
          when: manual
        - if: '$CI_COMMIT_TAG != null'
          when: never
        - if: '$CI_COMMIT_REF_NAME == "master"'
    variables:
        DOPPLER_TOKEN_MAIN: $DOPPLER_TOKEN_MAIN_PRE
        DOPPLER_TOKEN_ROUTE53: $DOPPLER_TOKEN_ROUTE53_PRE
        ENV: pre

deploy-pro:
    extends:
        - .deploy
    rules:
        - if: '$CI_COMMIT_TAG != null'
          when: manual
    variables:
        DOPPLER_TOKEN_MAIN: $DOPPLER_TOKEN_MAIN_PRO
        DOPPLER_TOKEN_ROUTE53: $DOPPLER_TOKEN_ROUTE53_PRO
        ENV: pro
